parameters: {}
environment: {}
packages:
  - name: website
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: gmail
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          CREDENTIALS: |
            ${CREDENTIALS}
          GMAIL: |
            ${GMAIL}
        limits:
          memory: 1024
          timeout: 10000
      - name: sheets
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          CREDENTIALS: |
            ${CREDENTIALS}
          SHEETS: |
            ${SHEETS}
        limits:
          memory: 1024
          timeout: 10000
      - name: sheets
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          BUCKET: |
            ${BUCKET}
          SECRET: |
            ${SECRET}
          REGION: |
            ${SECRET}
          KEY: |
            ${KEY}
        limits:
          memory: 1024
          timeout: 10000
