parameters: {}
environment: {}
packages:
  - name: website
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: mail
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          WEBHOOK: "${WEBHOOK}"
          CREDENTIALS: |
            ${CREDENTIALS}
          GMAIL: |
            ${GMAIL}
          SHEETS: |
            ${SHEETS}
        limits:
          memory: 1024
          timeout: 10000
      - name: upload
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          REGION: "${REGION}"
          BUCKET: "${BUCKET}"
          KEY: "${KEY}"
          SECRET: "${SECRET}"
        limits:
          memory: 1024
          timeout: 10000
      - name: partner
        binary: false
        main: ""
        runtime: go:1.20
        web: true
        webSecure: false
        environment:
          REGION: "${REGION}"
          BUCKET: "${BUCKET}"
          KEY: "${KEY}"
          SECRET: "${SECRET}"
        limits:
          memory: 1024
          timeout: 10000
