name: deploy-digitalocean-functions
on: [push, workflow_dispatch]
jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: install serverless plugin
        run: doctl serverless install

      - name: connect to serverless namespace
        run: doctl serverless connect

      - name: deploy functions
        run: doctl serverless deploy .
        env:
          BUCKET: ${{ secrets.BUCKET }}
          SECRET: ${{ secrets.SECRET }}
          REGION: ${{ secrets.REGION }}
          KEY: ${{ secrets.KEY }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          GMAIL: ${{ secrets.GMAIL }}
          SHEETS: ${{ secrets.SHEETS }}
