name: deploy-digitalocean-functions
on: [push, workflow_dispatch]
jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: install serverless plugin
        run: doctl serverless install

      - name: connect to serverless namespace
        run: doctl serverless connect

      - name: deploy functions
        run: doctl serverless deploy .
        env:
          BUCKET: ${{ secrets.BUCKET }}
          SECRET: ${{ secrets.SECRET }}
          REGION: ${{ secrets.REGION }}
          KEY: ${{ secrets.KEY }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          GMAIL: ${{ secrets.GMAIL }}
          SHEETS: ${{ secrets.SHEETS }}

      - name: verify validity of credentials
        run: |
          [[ $(curl -X POST "https://faas-fra1-afec6ce7.doserverless.co/api/v1/web/fn-70cb3437-eee1-474d-8ad6-387035b15671/website/sheets" -H "Content-Type: application/json" -d '{"id":"1WX6vvcCJihBJ9tFN-8AixYAyt5i1nSfMeX81gsEEwjs","range":"A:AL"}' | jq '.data | length') -gt 10 ]] && exit 0 || exit 1
