name: deploy-digitalocean-functions
on: [push, workflow_dispatch]
jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: deploy functions
        run: doctl serverless deploy .
        env:
          BUCKET: ${{ secrets.BUCKET }}
          SECRET: ${{ secrets.SECRET }}
          REGION: ${{ secrets.REGION }}
          KEY: ${{ secrets.KEY }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          GMAIL: ${{ secrets.GMAIL }}
          SHEETS: ${{ secrets.SHEETS }}
